[project]
name = "com519"
version = "0.1.0"
description = "Project for my COM519 Advanced databases module"
authors = [
    {name = "Daksh Sharma",email = "0shard85@solent.ac.uk"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "cryptography (>=46.0.3,<47.0.0)",
    "pillow (>=12.1.0,<13.0.0)"
]

[tool.poetry]
packages = [{include = "com519", from = "src"}]

[tool.poetry.scripts]
tkinter-app = "com519.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyinstaller (>=6.16.0,<7.0.0)"
]
